---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: konkservices.konk.infoblox.com
spec:
  group: konk.infoblox.com
  names:
    kind: KonkService
    listKind: KonkServiceList
    plural: konkservices
    singular: konkservice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KonkService is the Schema for the konkservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KonkService
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              konk:
                type: object
                properties:
                  name:
                    description: The name of the konk to create the APIService in.
                    type: string
                required:
                - name
                x-kubernetes-preserve-unknown-fields: true
              service:
                type: object
                properties:
                  name:
                    description: The name of your extension API service
                    type: string
                required:
                - name
                x-kubernetes-preserve-unknown-fields: true
            required:
              - konk
              - service
          status:
            description: Status defines the observed state of KonkService
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    additionalPrinterColumns:
    - name: Konk
      type: string
      jsonPath: .spec.konk.name
    - name: APIService
      type: string
      jsonPath: .spec.service.name
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    served: true
    storage: true
    subresources:
      status: {}
